#include "lvsgi/BinaryCache.hpp"
#include <fstream>
#include <algorithm>
#include <chrono>
namespace lvsgi { namespace { constexpr std::uint32_t MAGIC=0x4947564c; struct Header{std::uint32_t magic,version,format,size;}; }
BinaryCache::~BinaryCache(){stop();}
void BinaryCache::start(std::filesystem::path r,std::size_t b,std::size_t e){stop();root_=std::move(r);maxBytes_=b;maxEntries_=e;stop_=false;ready_=false;thread_=std::thread([this]{worker();});}
void BinaryCache::stop(){ {std::lock_guard l(mu_);stop_=true;}cv_.notify_all();if(thread_.joinable())thread_.join();std::lock_guard l(mu_);mem_.clear();writes_.clear();ready_=false;}
std::shared_ptr<const ProgramBinary> BinaryCache::find(const std::string&k)const{std::lock_guard l(mu_);auto i=mem_.find(k);return i==mem_.end()?nullptr:i->second;}
void BinaryCache::storeAsync(std::string k,std::uint32_t f,std::vector<std::uint8_t>b){auto p=std::make_shared<ProgramBinary>();p->format=f;p->bytes=std::move(b);{std::lock_guard l(mu_);mem_[k]=p;writes_.emplace_back(std::move(k),p);}cv_.notify_one();}
void BinaryCache::worker(){std::error_code ec;std::filesystem::create_directories(root_,ec);preload();{std::lock_guard l(mu_);ready_=true;}while(true){std::pair<std::string,std::shared_ptr<ProgramBinary>> w;{std::unique_lock l(mu_);cv_.wait(l,[&]{return stop_||!writes_.empty();});if(stop_&&writes_.empty())break;w=std::move(writes_.front());writes_.pop_front();}writeOne(w.first,*w.second);trim();}}
void BinaryCache::preload(){std::vector<std::filesystem::directory_entry> es;std::error_code ec;for(auto&i:std::filesystem::directory_iterator(root_,ec))if(i.is_regular_file()&&i.path().extension()==".lvbin")es.push_back(i);std::sort(es.begin(),es.end(),[](auto&a,auto&b){return a.last_write_time()>b.last_write_time();});std::size_t bytes=0,count=0;for(auto&e:es){if(count>=maxEntries_||bytes>=maxBytes_)break;std::ifstream f(e.path(),std::ios::binary);Header h{};f.read((char*)&h,sizeof h);if(!f||h.magic!=MAGIC||h.version!=1||h.size>64u*1024u*1024u)continue;auto p=std::make_shared<ProgramBinary>();p->format=h.format;p->bytes.resize(h.size);f.read((char*)p->bytes.data(),h.size);if(!f)continue;bytes+=p->bytes.size();count++;auto k=e.path().stem().string();std::lock_guard l(mu_);mem_[k]=std::move(p);}}
void BinaryCache::writeOne(const std::string&k,const ProgramBinary&p){auto tmp=root_/(k+".tmp"),dst=root_/(k+".lvbin");std::ofstream f(tmp,std::ios::binary|std::ios::trunc);Header h{MAGIC,1,p.format,(std::uint32_t)p.bytes.size()};f.write((char*)&h,sizeof h);f.write((char*)p.bytes.data(),p.bytes.size());f.flush();f.close();std::error_code ec;std::filesystem::rename(tmp,dst,ec);if(ec){std::filesystem::remove(dst,ec);ec.clear();std::filesystem::rename(tmp,dst,ec);}}
void BinaryCache::trim(){std::vector<std::filesystem::directory_entry>es;std::error_code ec;std::size_t bytes=0;for(auto&i:std::filesystem::directory_iterator(root_,ec))if(i.is_regular_file()&&i.path().extension()==".lvbin"){es.push_back(i);bytes+=i.file_size();}std::sort(es.begin(),es.end(),[](auto&a,auto&b){return a.last_write_time()<b.last_write_time();});while((es.size()>maxEntries_||bytes>maxBytes_)&&!es.empty()){auto e=es.front();es.erase(es.begin());auto s=e.file_size();std::filesystem::remove(e.path(),ec);if(bytes>=s)bytes-=s;std::lock_guard l(mu_);mem_.erase(e.path().stem().string());}}
} // namespace lvsgi
